#!/usr/bin/env python3
"""Write wii_stubs.c: a definition for every symbol the Wii link is missing.

    gen_stubs.py <link.log> <relocs.txt> <out.c>

link.log is the first link's output, whose "undefined reference to" lines
name what no unit defines: the parts of the Xbox SDK and of the Linux port's
platform layer the Wii layer has no code for yet. relocs.txt is
`objdump -r` over the objects, which says how each is used. A symbol only
ever called (R_PPC_REL24, a `bl`) becomes a function that names itself on
the console the first time it runs and returns 0, which the SDK's callers
read as failure, NULL or "nothing there". Anything else is data and becomes
zeroed storage. Each one goes when a stage of the plan gives it real code.
"""
import re
import sys

log, relocs, out = sys.argv[1:4]
missing = sorted(set(re.findall(r"undefined reference to [`'](\w+)'", open(log).read())))
kinds = {}
for line in open(relocs):
    parts = line.split()
    if len(parts) == 3 and parts[1].startswith("R_PPC"):
        kinds.setdefault(re.sub(r"[+-]0x.*", "", parts[2]), set()).add(parts[1])

lines = [
    "/* generated by port/wii/gen_stubs.py from the link's undefined references: do not edit */",
    "",
    "void platform_unimplemented(const char *name);",
    "",
]
functions = data = 0
for name in missing:
    if "R_PPC_REL24" in kinds.get(name, ()):
        lines.append(
            f"int {name}(void) {{ static int said; if (!said) {{ said = 1; "
            f'platform_unimplemented("{name}"); }} return 0; }}')
        functions += 1
    else:
        lines.append(f"unsigned char {name}[4096] __attribute__((aligned(32)));")
        data += 1
open(out, "w").write("\n".join(lines) + "\n")
print(f"wii_stubs.c: {functions} functions, {data} data")
