/*
WII_MAIN.C

The Wii's entry point, around the game's own main() (shell_xbox.c). The link
wraps main (-Wl,--wrap=main): libogc's start-up calls __wrap_main here, which
brings up the video and the text console, then runs the game's main as
__real_main. Everything the game logs (d:\debug.txt, see wii_crt.c) and
everything this layer logs goes to that console, and to sd:/halo/debug.txt
when there is a card.

This file sees libogc and not the XDK, whose names (BOOL, u32, ...) clash
with libogc's.
*/

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gccore.h>

#include "../halo_wii_capacity.h"
#include "wii_os.h"

int __real_main(int argc, char **argv);

static void *framebuffer;
static GXRModeObj *video_mode;

/* ---------- logging (platform.h) */

void platform_log(const char *format, ...)
{
	va_list arguments;

	fputs("wii: ", stdout);
	va_start(arguments, format);
	vprintf(format, arguments);
	va_end(arguments);
	fputs("\n", stdout);
}

/* an SDK entry point the Wii layer does not implement yet: named the first
time it is called (wii_stubs.c, generated by port/wii/gen_stubs.py) */
void platform_unimplemented(const char *name)
{
	platform_log("stub: %s", name);
}

/* ---------- start-up */

static void video_initialize(void)
{
	VIDEO_Init();
	video_mode = VIDEO_GetPreferredMode(NULL);
	framebuffer = MEM_K0_TO_K1(SYS_AllocateFramebuffer(video_mode));
	console_init(framebuffer, 16, 16, video_mode->fbWidth, video_mode->xfbHeight,
		video_mode->fbWidth * VI_DISPLAY_PIX_SZ);
	VIDEO_Configure(video_mode);
	VIDEO_SetNextFramebuffer(framebuffer);
	VIDEO_SetBlack(FALSE);
	VIDEO_Flush();
	VIDEO_WaitVSync();
	if (video_mode->viTVMode & VI_NON_INTERLACE)
		VIDEO_WaitVSync();
}

/* show what is on the console until the power goes, rather than going back
to the loader with the log gone */
static void hold_screen(void)
{
	for (;;)
		VIDEO_WaitVSync();
}

/* keep the game's fixed places (halo_wii_capacity.h) out of the heap: the
top of MEM1 and the foot of MEM2, before anything is allocated there */
static void reserve_fixed_places(void)
{
	SYS_SetArena1Hi((void *)HALO_PORT_GAME_STATE_BASE_ADDRESS);
	SYS_SetArena2Lo((void *)HALO_WII_FIXED_PLACES_END);
}

int __wrap_main(int argc, char **argv)
{
	int result;

	reserve_fixed_places();
	video_initialize();
	/* the game's threads run at main's priority (wii_os.c) */
	LWP_SetThreadPriority(LWP_GetSelf(), 64);
	if (wii_storage_mount())
		wii_console_log_to_storage();
	printf("\x1b[2;0H");
	printf("Halo: Combat Evolved for the Wii (stub platform layer)\n");
	printf("heap: MEM1 %p-%p, MEM2 %p-%p\n",
		SYS_GetArena1Lo(), SYS_GetArena1Hi(), SYS_GetArena2Lo(), SYS_GetArena2Hi());
	printf("data: %s\n\n", wii_data_root() ? "sd:/halo (this log is sd:/halo/debug.txt)" : "no SD card");

	result = __real_main(argc, argv);

	platform_log("the game's main returned %d", result);
	hold_screen();
	return result;
}

/* the game ends with exit() when an assert fails (system_exit): keep the
log on screen instead */
void __wrap_exit(int status)
{
	platform_log("exit(%d)", status);
	hold_screen();
	for (;;);
}
